### ISSUE TITLE
(Mac OS related ?) bugs

### ISSUE THREAD

**Issue by jmarceli** [Mte90/generator-wp-plugin-boilerplate-powered#11]
After downloading last release I've checked everything once more. Now on Mac your version of the script (0159e7f3255ed8ba192aedcda092ad3565dcb482) generates two main files: `yourplugin.php` and `yourplugin.php.php`, mine version (03f9545dbb8cd6604ee8fc745be7d29dbf509d90) is fine (only one file).

What is more **both** solutions doesn't work well with enabling/disabling libraries from `includes/` folder. 
With `default-values.json`:

```
{
  "name": "some_name",
  "pluginVersion": "1.0.0",
  "author": {
    "name": "Jan",
    "email": "myemail@gmail.com",
    "url": "",
    "copyright": ""
  },
  "authorURI": "",
  "publicResources": [],
  "activateDeactivate": [],
  "adminPage": true,
  "modules": [
    "CPT_Core",
    "CPT_Columns",
    "CMB2"
  ],
  "snippet": [],
  "git": true,
  "cleanFolder": true,
  "saveSettings": false
}
```

I get following errors:

In mymodule.php
Unbalanced comments and template, widget plugins are not commented out.
```
/*
 * Load library for simple and fast creation of  Custom Post Type
 */
require_once( plugin_dir_path( __FILE__ ) . 'includes/CPT_Core/CPT_Core.php' );
require_once( plugin_dir_path( __FILE__ ) . 'includes/template.php' );
require_once( plugin_dir_path( __FILE__ ) . 'includes/widgets/sample.php' );
*/
```

In `public/class-mymodule.php`:
Unbalanced comments while `single_deactive()` should be probably commented out (I didn't check it during configuration)
```
}
	 * @since    1.0.0
	 */
	private static function single_deactivate() {
		// @TODO: Define deactivation functionality here
		//Clear the permalinks
		flush_rewrite_rules();
	}
```

Too many closing brackets:
```
	/**
	 * Register and enqueues public-facing JavaScript files.
	 *
	 * @since    1.0.0
	 */
	public function enqueue_scripts() {
		wp_enqueue_script( $this->get_plugin_slug() . '-plugin-script', plugins_url( 'assets/js/public.js', __FILE__ ), array( 'jquery' ), self::VERSION );
	}
	}
	}
	}
```

In `admin/class-mymodule-admin.php`:
Closing brackets issue:
```
	public function add_action_links( $links ) {
		return array_merge(
				array(
			'settings' => '<a href="' . admin_url( 'options-general.php?page=' . $this->plugin_slug ) . '">' . __( 'Settings' ) . '</a>',
			'donate' => '<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=danielemte90@alice.it&item_name=Donation">' . __( 'Donate', $this->plugin_slug ) . '</a>'
				), $links
		);
	}
	}
		return $items;
	}
	}
```

And some more minor bugs in `admin/class-mymodule-admin.php`.

It might be somehow related to `sed` in Mac OS X Yosemite, I don't know.

**Comment by jmarceli** [comment]
Disabling settings page in configuration doesn't remove settings link from plugin admin Panel.

**Comment by jmarceli** [comment]
It does work well if I leave everything enabled during configuration process.

**Comment by Mte90** [comment]
I've released a new version that fix the4 extension problem.
I think that the other problems that you have was from that problem.
