### ISSUE TITLE
sed stderr on OSX (El Capitan)

### ISSUE THREAD

**Issue by manueleone** [Mte90/generator-wp-plugin-boilerplate-powered#17]
Hi,

I am playing with your generator but I got some errors at the end of the process.
When "_sed command and replace method_" is called, it returns "_No such file or directory_" on some files, so I had to change two lines in **raplacer.js** to make it work:

On line 152:
`sedcmd = "sed -i '" + path.extname(file) + "' '" + line + "' " + process.cwd() + '/' + file.substr(0, file.lastIndexOf("."));`
Changed with:
`sedcmd = "sed -i '' '" + line + "' " + process.cwd() + '/' + file;`

On line 171: 
`sedcmd = "sed -i '" + path.extname(file) + "' '/^$/N;/^\\n$/D' " + process.cwd() + '/' + file.substr(0, file.lastIndexOf("."));`
Changed with:
sedcmd = "sed -i '' '/^$/N;/^\\n$/D' " + process.cwd() + '/' + file;

Thanks for your great work!

**Comment by Mte90** [comment]
I have to investigate ASAP because I don't have a OSX system to test and in the past we have added a check for that system because the sed command is different from linux.

Thanks for your ticket!

**Comment by Mte90** [comment]
As i can see you have the GNU version of sed for OSX (http://stackoverflow.com/questions/30003570/how-to-use-gnu-sed-on-mac-os-x) but on https://github.com/Mte90/generator-wp-plugin-boilerplate-powered/pull/8 we saw that the sed is different on OSX.
I can add a check for `gsed`.

**Comment by Mte90** [comment]
Can you check what is your `sed` type?

**Comment by manueleone** [comment]
Sure, how can I check? 
`which sed` returns `/usr/bin/sed`

**Comment by Mte90** [comment]
If you do `sed --version` what is the output?

**Comment by manueleone** [comment]
I was asking because with `sed --version` I only get:
```
sed: illegal option -- -
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

**Comment by manueleone** [comment]
Maybe instead of trying to fix the script, you can add "gnu-like sed" as a prerequisite!
So a mac user needs to install it with brew for example to have it working the same.
After `brew install gnu-sed` I have sed (GNU sed) 4.2.2, then the generator runs perfectly (after removing the no more needed check on platform in replacer.js).

**Comment by Mte90** [comment]
Actually the generator support osx with their sed version but i think that you have a different version of sed that is unix.
I have to investigate maybe i can detect what is your sed without problem.

**Comment by Mte90** [comment]
I have added an alert about gsed and the system detect that or the naive sed version without problems.

**Comment by manueleone** [comment]
Thank you ;)
