### ISSUE TITLE
Error on submodule:Cloning into 'admin/includes/CMB2'...

### ISSUE THREAD

**Issue by encodia** [Mte90/generator-wp-plugin-boilerplate-powered#18]
Hi,

I am getting this error: `Error on submodule:Cloning into 'admin/includes/CMB2'...`, sending:

`sudo yo wp-plugin-boilerplate-powered dev` or `sudo yo wp-plugin-boilerplate-powered`

I am using vagrant.

**Comment by Mte90** [comment]
Uhm this error is very strange and happen when there are problem on download the submodule.
In the machine there is git?

**Comment by encodia** [comment]
Hi Mte90, yes there is git.
Thanks

**Comment by Mte90** [comment]
https://github.com/Mte90/generator-wp-plugin-boilerplate-powered/blob/master/app%2Findex.js#L176
This is the script that is executed and generate the error, the problem happen probably on `git submodule add -f $url $path >> /dev/null`.
The machine is connected to internet?

**Comment by encodia** [comment]
Yes @Mte90, machine is connected to internet. What can I do to debug?

**Comment by Mte90** [comment]
is very strange, when i use the generator i do it locally on the file shared with the vagrant machine.

**Comment by encodia** [comment]
Ehm... I can't do it locally, 'cause - unlucky - I am using Windows...

**Comment by Mte90** [comment]
I have no idea of that problem :-/

**Comment by encodia** [comment]
Ok, I will try on a different machine. Thanks :-/

**Comment by Mte90** [comment]
I see that problem on my system, try with the new release 
https://github.com/Mte90/generator-wp-plugin-boilerplate-powered/releases/tag/0.2.3

`npm install -g generator-wp-plugin-boilerplate-powered`

**Comment by Mte90** [comment]
Ok today I get that error and in the new last version i hope that now works without problems https://github.com/Mte90/generator-wp-plugin-boilerplate-powered/releases/tag/0.2.4
